global:
  scrape_interval: 5s
  external_labels:
    monitor: 'devopsage-monitor'

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.31.26.111:9090']
  - job_name: 'node-exporter' 
    static_configs: 
      - targets: ['172.31.26.111:9100']
  - job_name: 'cAdvisor'
    static_configs:
      - targets: ['172.31.26.111:8080']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "172.31.26.111:9093"
